"""Wyckoff schematic event detection and contextual analysis."""

from wyckoff_screener.wyckoff.events import WyckoffEvent
from wyckoff_screener.wyckoff.schematic_events import (
    AR_MAX_BARS_AFTER_SC,
    AR_MIN_VOLUME_RATIO,
    LPS_LOOKBACK,
    LPS_MAX_BARS_AFTER_ANCHOR,
    LPS_MAX_VOLUME_RATIO,
    SC_MIN_DECLINE_PCT,
    SC_MIN_SPREAD_RATIO,
    SC_MIN_VOLUME_RATIO,
    SOS_LOOKBACK,
    SOS_MIN_CLOSE_POSITION,
    SOS_MIN_VOLUME_RATIO,
    SPRING_LOOKBACK,
    ST_MAX_BARS_AFTER_SC,
    ST_PRICE_TOLERANCE_PCT,
    UTAD_LOOKBACK,
    UTAD_MIN_VOLUME_RATIO,
    detect_all_schematic_events,
    detect_automatic_rally_candidates,
    detect_lps_candidates,
    detect_secondary_test_candidates,
    detect_selling_climax_candidates,
    detect_sos_candidates,
    detect_spring_candidates,
    detect_utad_candidates,
)
from wyckoff_screener.wyckoff.swing_points import (
    TradingRangeContext,
    detect_prior_decline,
    get_prior_trading_range,
    is_swing_high,
    is_swing_low,
)

__all__ = [
    "WyckoffEvent",
    "TradingRangeContext",
    "is_swing_low",
    "is_swing_high",
    "detect_prior_decline",
    "get_prior_trading_range",
    "detect_selling_climax_candidates",
    "detect_automatic_rally_candidates",
    "detect_secondary_test_candidates",
    "detect_spring_candidates",
    "detect_lps_candidates",
    "detect_sos_candidates",
    "detect_utad_candidates",
    "detect_all_schematic_events",
    "SC_MIN_SPREAD_RATIO",
    "SC_MIN_VOLUME_RATIO",
    "SC_MIN_DECLINE_PCT",
    "AR_MIN_VOLUME_RATIO",
    "AR_MAX_BARS_AFTER_SC",
    "ST_PRICE_TOLERANCE_PCT",
    "ST_MAX_BARS_AFTER_SC",
    "SPRING_LOOKBACK",
    "LPS_MAX_VOLUME_RATIO",
    "LPS_LOOKBACK",
    "LPS_MAX_BARS_AFTER_ANCHOR",
    "SOS_MIN_VOLUME_RATIO",
    "SOS_MIN_CLOSE_POSITION",
    "SOS_LOOKBACK",
    "UTAD_MIN_VOLUME_RATIO",
    "UTAD_LOOKBACK",
]
