"""High-Throughput Historical Backtesting Engine for Google Sheets & Excel Export.

Guiding Principles (AGENTS.md & Phase 16):
1. Strict Point-in-Time Signal Generation:
   For historical signal date T, the screener calculates signals using ONLY OHLCV data on or before T (df[df['Date'] <= T]).
   No future data is ever visible during signal calculation.
2. Next-Day Open Entry Model:
   Entry occurs on the next available market trading day Open (T+1 Open).
3. Forward Horizons:
   Calculates returns across 5d, 10d, 20d, 30d, 60d, and 90d trading days.
4. Comprehensive Risk Metrics:
   Calculates Maximum Favorable Excursion (MFE), Maximum Adverse Excursion (MAE), and Maximum Drawdown.
5. High-Throughput Stock-Batched Execution:
   Processes symbols concurrently with vectorized indicator indexing and zero redundant re-parsing.
6. Google Sheets / Excel Multi-Tab Deliverables:
   Generates both modular CSVs and phase16_google_sheets_backtest.xlsx.
"""

from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import time
from typing import Any, Final, Optional, Sequence
import numpy as np
import pandas as pd

from wyckoff_screener.backtest.signal_generator import (
    DEFAULT_ENTRY_MODEL,
    DEFAULT_HIGH_PRIORITY_THRESH,
    DEFAULT_MIN_BARS,
    DEFAULT_MIN_TURNOVER_CR,
    DEFAULT_QUALIFIED_THRESH,
    DEFAULT_SURVIVORSHIP_BIAS_STATUS,
    DEFAULT_WATCHLIST_THRESH,
    determine_historical_signal_dates,
    evaluate_point_in_time_signal,
)
from wyckoff_screener.data_loader import validate_ohlcv_dataframe

DEFAULT_FORWARD_HORIZONS: Final[tuple[int, ...]] = (5, 10, 20, 30, 60, 90)
DEFAULT_FRICTION_PCT: Final[float] = 0.40  # 10 bps transaction cost + 10 bps slippage each way (0.40% round-trip)


def compute_forward_returns_and_risk(
    signal_record: dict[str, Any],
    full_price_df: pd.DataFrame,
    horizons: Sequence[int] = DEFAULT_FORWARD_HORIZONS,
    date_col: str = "Date",
    open_col: str = "Open",
    high_col: str = "High",
    low_col: str = "Low",
    close_col: str = "Close",
    friction_pct: float = DEFAULT_FRICTION_PCT,
) -> dict[str, Any]:
    """Compute forward returns, MFE, MAE, and max drawdown for a single historical signal.

    Args:
        signal_record: Dictionary generated by evaluate_point_in_time_signal().
        full_price_df: Full historical daily OHLCV DataFrame for the stock.
        horizons: Sequence of trading day horizons (5, 10, 20, 30, 60, 90).
        friction_pct: Round-trip trading friction percentage (default 0.40%).

    Returns:
        dict[str, Any]: Augmented dictionary containing entry price, exit prices, forward returns, MFE, MAE.
    """
    out = dict(signal_record)
    sig_date = pd.to_datetime(signal_record["signal_date"])

    pdf = full_price_df.copy()
    pdf[date_col] = pd.to_datetime(pdf[date_col])
    pdf = pdf.sort_values(by=date_col).reset_index(drop=True)

    # Locate signal bar index in full price series
    sig_matches = pdf.index[pdf[date_col] == sig_date].tolist()
    if not sig_matches:
        earlier_matches = pdf.index[pdf[date_col] <= sig_date].tolist()
        if not earlier_matches:
            return out
        sig_idx = earlier_matches[-1]
    else:
        sig_idx = sig_matches[0]

    total_bars = len(pdf)
    entry_idx = sig_idx + 1

    if entry_idx >= total_bars:
        # Signal occurred on latest bar; no forward bars exist
        out["entry_date"] = "PENDING_FUTURE"
        out["entry_price"] = None
        for h in horizons:
            out[f"fwd_ret_{h}d"] = None
            out[f"fwd_net_ret_{h}d"] = None
            out[f"exit_price_{h}d"] = None
        out["mfe_pct"] = None
        out["mae_pct"] = None
        out["max_drawdown_pct"] = None
        return out

    # Entry Model: Next available trading day Open (T+1 Open)
    entry_date = str(pdf[date_col].iloc[entry_idx])[:10]
    entry_price = float(pdf[open_col].iloc[entry_idx])
    out["entry_date"] = entry_date
    out["entry_price"] = round(entry_price, 2)

    # Calculate returns for each horizon
    max_h = max(horizons)
    eval_end_idx = min(total_bars - 1, entry_idx + max_h)

    for h in horizons:
        target_idx = entry_idx + h
        if target_idx < total_bars:
            exit_p = float(pdf[close_col].iloc[target_idx])
            gross_ret = ((exit_p - entry_price) / entry_price) * 100.0
            net_ret = gross_ret - friction_pct
            out[f"exit_price_{h}d"] = round(exit_p, 2)
            out[f"fwd_ret_{h}d"] = round(gross_ret, 2)
            out[f"fwd_net_ret_{h}d"] = round(net_ret, 2)
        else:
            out[f"exit_price_{h}d"] = None
            out[f"fwd_ret_{h}d"] = None
            out[f"fwd_net_ret_{h}d"] = None

    # Calculate Excursions & Drawdowns over available forward window
    forward_slice = pdf.iloc[entry_idx : eval_end_idx + 1]
    if not forward_slice.empty and entry_price > 0:
        max_high = float(forward_slice[high_col].max())
        min_low = float(forward_slice[low_col].min())
        mfe = ((max_high - entry_price) / entry_price) * 100.0
        mae = ((min_low - entry_price) / entry_price) * 100.0

        cum_max = forward_slice[high_col].cummax()
        drawdown_series = (forward_slice[low_col] - cum_max) / cum_max * 100.0
        max_dd = float(drawdown_series.min())

        out["mfe_pct"] = round(mfe, 2)
        out["mae_pct"] = round(mae, 2)
        out["max_drawdown_pct"] = round(max_dd, 2)
    else:
        out["mfe_pct"] = None
        out["mae_pct"] = None
        out["max_drawdown_pct"] = None

    return out


def evaluate_symbol_all_dates(
    symbol: str,
    raw_df: pd.DataFrame,
    target_dates: Sequence[str],
    yfinance_ticker: Optional[str] = None,
    company_name: Optional[str] = None,
    min_bars: int = DEFAULT_MIN_BARS,
    min_avg_turnover_cr: float = DEFAULT_MIN_TURNOVER_CR,
    backtest_run_id: str = "backtest",
) -> list[dict[str, Any]]:
    """Evaluate point-in-time signals for a single stock across all historical dates.

    Guarantees strict point-in-time isolation by evaluating df[df['Date'] <= as_of_date].
    """
    results: list[dict[str, Any]] = []
    if raw_df.empty or "Date" not in raw_df.columns:
        return results

    clean_df = validate_ohlcv_dataframe(raw_df).sort_values(by="Date").reset_index(drop=True)
    clean_df["Date"] = pd.to_datetime(clean_df["Date"])

    for dt_str in target_dates:
        target_ts = pd.to_datetime(dt_str)
        pit_df = clean_df[clean_df["Date"] <= target_ts]
        if len(pit_df) < min_bars:
            continue

        sig = evaluate_point_in_time_signal(
            df=pit_df,
            symbol=symbol,
            as_of_date=dt_str,
            yfinance_ticker=yfinance_ticker,
            company_name=company_name,
            min_bars=min_bars,
            min_avg_turnover_cr=min_avg_turnover_cr,
            backtest_run_id=backtest_run_id,
        )
        if sig is not None:
            # Augment with forward returns & risk
            augmented = compute_forward_returns_and_risk(
                signal_record=sig,
                full_price_df=clean_df,
                horizons=DEFAULT_FORWARD_HORIZONS,
            )
            results.append(augmented)

    return results


def run_point_in_time_backtest(
    securities: list[tuple[str, pd.DataFrame, Optional[str], Optional[str]]],
    start_date: str = "2023-06-01",
    end_date: str = "2026-08-24",
    frequency: str = "monthly",
    min_bars: int = DEFAULT_MIN_BARS,
    min_avg_turnover_cr: float = DEFAULT_MIN_TURNOVER_CR,
    backtest_run_id: Optional[str] = None,
    universe_source: str = "watchlist",
    max_workers: int = 4,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    """Execute high-throughput point-in-time signal generation and forward return calculations."""
    start_t = time.time()
    run_id = backtest_run_id or f"backtest_{universe_source}_{frequency}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"

    # 1. Collect all dates to find market trading day alignments
    all_dates_set = set()
    for _, df, _, _ in securities:
        if not df.empty and "Date" in df.columns:
            all_dates_set.update(pd.to_datetime(df["Date"]))

    signal_dates = determine_historical_signal_dates(
        list(all_dates_set), start_date=start_date, end_date=end_date, frequency=frequency
    )

    print(f"\n[Phase 16] Starting historical backtest: {len(securities)} securities across {len(signal_dates)} signal dates...")

    # 2. Parallel stock-batched evaluation
    all_signals_returns: list[dict[str, Any]] = []
    completed_symbols = 0
    total_symbols = len(securities)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_sym = {
            executor.submit(
                evaluate_symbol_all_dates,
                symbol=sym,
                raw_df=df,
                target_dates=signal_dates,
                yfinance_ticker=yf_t,
                company_name=comp_n,
                min_bars=min_bars,
                min_avg_turnover_cr=min_avg_turnover_cr,
                backtest_run_id=run_id,
            ): sym
            for sym, df, yf_t, comp_n in securities
        }

        for future in as_completed(future_to_sym):
            sym = future_to_sym[future]
            try:
                sym_results = future.result()
                all_signals_returns.extend(sym_results)
                completed_symbols += 1
                elapsed = time.time() - start_t
                if completed_symbols % 5 == 0 or completed_symbols == total_symbols:
                    print(
                        f"[Phase 16] Processed {completed_symbols}/{total_symbols} symbols | "
                        f"Signals generated: {len(all_signals_returns)} | "
                        f"Elapsed: {elapsed:.1f}s"
                    )
            except Exception as e:
                print(f"[Phase 16] Error evaluating {sym}: {e}")

    df_signals = pd.DataFrame(all_signals_returns)
    if not df_signals.empty:
        df_signals = df_signals.sort_values(by=["signal_date", "composite_score"], ascending=[True, False]).reset_index(drop=True)

    # 3. Vectorized Panel Price table
    price_frames: list[pd.DataFrame] = []
    for sym, df, _, _ in securities:
        if df.empty or "Date" not in df.columns:
            continue
        v_df = validate_ohlcv_dataframe(df).sort_values(by="Date").reset_index(drop=True)
        pdf = pd.DataFrame({
            "Date": v_df["Date"].astype(str).str[:10],
            "Symbol": sym,
            "Trading_Day_Num": np.arange(1, len(v_df) + 1),
            "Open": v_df["Open"].round(2),
            "High": v_df["High"].round(2),
            "Low": v_df["Low"].round(2),
            "Close": v_df["Close"].round(2),
            "Volume": v_df["Volume"].astype(int),
        })
        price_frames.append(pdf)

    df_prices = pd.concat(price_frames, ignore_index=True) if price_frames else pd.DataFrame()

    # 4. Manifest
    total_signals = len(df_signals)
    hp_count = int((df_signals["is_high_priority"] == True).sum()) if not df_signals.empty else 0
    q_count = int((df_signals["is_qualified"] == True).sum()) if not df_signals.empty else 0
    w_count = int((df_signals["is_watchlist"] == True).sum()) if not df_signals.empty else 0
    disq_count = int((df_signals["is_disqualified"] == True).sum()) if not df_signals.empty else 0

    manifest = {
        "backtest_run_id": run_id,
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "schema_version": "1.0",
        "start_date": start_date,
        "end_date": end_date,
        "frequency": frequency,
        "universe_source": universe_source,
        "survivorship_bias_disclosure": DEFAULT_SURVIVORSHIP_BIAS_STATUS,
        "entry_model": DEFAULT_ENTRY_MODEL,
        "forward_horizons_bars": list(DEFAULT_FORWARD_HORIZONS),
        "total_symbols_evaluated": total_symbols,
        "total_historical_dates_evaluated": len(signal_dates),
        "total_signals_generated": total_signals,
        "high_priority_signals_count": hp_count,
        "qualified_signals_count": q_count,
        "watchlist_signals_count": w_count,
        "disqualified_signals_count": disq_count,
        "execution_duration_seconds": round(time.time() - start_t, 2),
    }

    return df_signals, df_prices, manifest


def export_backtest_workbook(
    signals_returns_df: pd.DataFrame,
    prices_df: pd.DataFrame,
    manifest: dict[str, Any],
    output_dir: Path | str,
) -> Path:
    """Generate the complete multi-tab Google Sheets/Excel workbook and companion CSVs."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    xlsx_path = out_dir / "phase16_google_sheets_backtest.xlsx"
    sig_csv_path = out_dir / "historical_signals.csv"
    ret_csv_path = out_dir / "backtest_returns.csv"
    prc_csv_path = out_dir / "historical_prices.csv"
    man_json_path = out_dir / "backtest_manifest.json"

    # Save CSV and JSON artifacts
    signals_returns_df.to_csv(ret_csv_path, index=False)
    signals_returns_df.to_csv(sig_csv_path, index=False)
    prices_df.to_csv(prc_csv_path, index=False)
    with open(man_json_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    # 1. Tab 1: README / CONFIG
    readme_data = [
        {"Section": "Backtest ID", "Value": manifest.get("backtest_run_id"), "Description": "Unique execution identifier"},
        {"Section": "Date Range", "Value": f"{manifest.get('start_date')} -> {manifest.get('end_date')}", "Description": "Historical evaluation span"},
        {"Section": "Frequency", "Value": manifest.get("frequency"), "Description": "Signal generation checkpoint interval"},
        {"Section": "Entry Model", "Value": manifest.get("entry_model"), "Description": "Next available trading day Open (T+1 Open)"},
        {"Section": "Transaction Cost (bps)", "Value": 10, "Description": "0.10% per transaction"},
        {"Section": "Slippage (bps)", "Value": 10, "Description": "0.10% per transaction"},
        {"Section": "Round-Trip Friction (%)", "Value": "0.40%", "Description": "Subtracted from gross return for net return"},
        {"Section": "Survivorship Bias", "Value": "Disclosed", "Description": manifest.get("survivorship_bias_disclosure")},
    ]
    df_readme = pd.DataFrame(readme_data)

    # 2. Tab 4: SUMMARY
    summary_rows = []
    for cat in ["HIGH_PRIORITY_CANDIDATE", "QUALIFIED_CANDIDATE", "WATCHLIST", "DISQUALIFIED", "ALL_SIGNALS"]:
        subset = signals_returns_df if cat == "ALL_SIGNALS" else signals_returns_df[signals_returns_df["candidate_category"] == cat]
        if not subset.empty:
            r20 = subset["fwd_ret_20d"].dropna()
            r60 = subset["fwd_ret_60d"].dropna()
            summary_rows.append({
                "Category": cat,
                "Count": len(subset),
                "Win_Rate_20D (%)": round((r20 > 0).mean() * 100, 1) if not r20.empty else 0.0,
                "Mean_Return_20D (%)": round(r20.mean(), 2) if not r20.empty else 0.0,
                "Median_Return_20D (%)": round(r20.median(), 2) if not r20.empty else 0.0,
                "Win_Rate_60D (%)": round((r60 > 0).mean() * 100, 1) if not r60.empty else 0.0,
                "Mean_Return_60D (%)": round(r60.mean(), 2) if not r60.empty else 0.0,
                "Median_Return_60D (%)": round(r60.median(), 2) if not r60.empty else 0.0,
                "Mean_MFE (%)": round(subset["mfe_pct"].dropna().mean(), 2) if not subset["mfe_pct"].dropna().empty else 0.0,
                "Mean_MAE (%)": round(subset["mae_pct"].dropna().mean(), 2) if not subset["mae_pct"].dropna().empty else 0.0,
                "Max_Drawdown (%)": round(subset["max_drawdown_pct"].dropna().min(), 2) if not subset["max_drawdown_pct"].dropna().empty else 0.0,
            })
    df_summary = pd.DataFrame(summary_rows)

    # 3. Tab 5: SCORE_ANALYSIS (Deciles)
    score_bins = [(80, 100), (70, 79.99), (60, 69.99), (50, 59.99), (40, 49.99), (0, 39.99)]
    score_rows = []
    for low, high in score_bins:
        sub = signals_returns_df[(signals_returns_df["composite_score"] >= low) & (signals_returns_df["composite_score"] <= high)]
        if not sub.empty:
            r20 = sub["fwd_ret_20d"].dropna()
            r60 = sub["fwd_ret_60d"].dropna()
            score_rows.append({
                "Score_Range": f"{low} - {high}",
                "Count": len(sub),
                "Win_Rate_20D (%)": round((r20 > 0).mean() * 100, 1) if not r20.empty else 0.0,
                "Mean_Return_20D (%)": round(r20.mean(), 2) if not r20.empty else 0.0,
                "Median_Return_20D (%)": round(r20.median(), 2) if not r20.empty else 0.0,
                "Win_Rate_60D (%)": round((r60 > 0).mean() * 100, 1) if not r60.empty else 0.0,
                "Mean_Return_60D (%)": round(r60.mean(), 2) if not r60.empty else 0.0,
                "Median_Return_60D (%)": round(r60.median(), 2) if not r60.empty else 0.0,
                "Mean_MFE (%)": round(sub["mfe_pct"].dropna().mean(), 2) if not sub["mfe_pct"].dropna().empty else 0.0,
                "Mean_MAE (%)": round(sub["mae_pct"].dropna().mean(), 2) if not sub["mae_pct"].dropna().empty else 0.0,
            })
    df_score_analysis = pd.DataFrame(score_rows)

    # 4. Tab 6: SIGNAL_TYPE_ANALYSIS
    event_rows = []
    for ev in ["Spring", "LPS", "SOS", "ST", "SC", "AR", "UTAD"]:
        sub = signals_returns_df[signals_returns_df["most_recent_event_type"] == ev]
        if not sub.empty:
            r20 = sub["fwd_ret_20d"].dropna()
            r60 = sub["fwd_ret_60d"].dropna()
            event_rows.append({
                "Wyckoff_Event": ev,
                "Count": len(sub),
                "Win_Rate_20D (%)": round((r20 > 0).mean() * 100, 1) if not r20.empty else 0.0,
                "Mean_Return_20D (%)": round(r20.mean(), 2) if not r20.empty else 0.0,
                "Median_Return_20D (%)": round(r20.median(), 2) if not r20.empty else 0.0,
                "Win_Rate_60D (%)": round((r60 > 0).mean() * 100, 1) if not r60.empty else 0.0,
                "Mean_Return_60D (%)": round(r60.mean(), 2) if not r60.empty else 0.0,
                "Median_Return_60D (%)": round(r60.median(), 2) if not r60.empty else 0.0,
                "Mean_MFE (%)": round(sub["mfe_pct"].dropna().mean(), 2) if not sub["mfe_pct"].dropna().empty else 0.0,
                "Mean_MAE (%)": round(sub["mae_pct"].dropna().mean(), 2) if not sub["mae_pct"].dropna().empty else 0.0,
            })
    df_signal_type = pd.DataFrame(event_rows)

    # 6. Tab 7: BENCHMARK (Universe Equal-Weighted Baseline)
    benchmark_rows = []
    for sig_date in signals_returns_df["signal_date"].unique():
        sub = signals_returns_df[signals_returns_df["signal_date"] == sig_date]
        r20 = sub["fwd_ret_20d"].dropna()
        hp_sub = sub[sub["candidate_category"] == "HIGH_PRIORITY_CANDIDATE"]
        q_sub = sub[sub["candidate_category"] == "QUALIFIED_CANDIDATE"]
        hp_r20 = hp_sub["fwd_ret_20d"].dropna().mean() if not hp_sub.empty else None
        q_r20 = q_sub["fwd_ret_20d"].dropna().mean() if not q_sub.empty else None

        benchmark_rows.append({
            "Signal_Date": sig_date,
            "Universe_Mean_20D (%)": round(r20.mean(), 2) if not r20.empty else None,
            "High_Priority_Mean_20D (%)": round(hp_r20, 2) if hp_r20 is not None else None,
            "Qualified_Mean_20D (%)": round(q_r20, 2) if q_r20 is not None else None,
            "High_Priority_Alpha (%)": round(hp_r20 - r20.mean(), 2) if hp_r20 is not None and not r20.empty else None,
        })
    df_benchmark = pd.DataFrame(benchmark_rows)

    # 7. Tab: YEAR_ANALYSIS (2023, 2024, 2025, 2026)
    signals_returns_df["signal_year"] = pd.to_datetime(signals_returns_df["signal_date"]).dt.year.astype(str)
    year_rows = []
    for yr in sorted(signals_returns_df["signal_year"].unique()):
        yr_sub = signals_returns_df[signals_returns_df["signal_year"] == yr]
        yr_hp = yr_sub[yr_sub["candidate_category"] == "HIGH_PRIORITY_CANDIDATE"]
        yr_q = yr_sub[yr_sub["candidate_category"] == "QUALIFIED_CANDIDATE"]
        r20_all = yr_sub["fwd_ret_20d"].dropna()
        r20_hp = yr_hp["fwd_ret_20d"].dropna()
        r20_q = yr_q["fwd_ret_20d"].dropna()
        r60_hp = yr_hp["fwd_ret_60d"].dropna()

        year_rows.append({
            "Year": yr,
            "Total_Signals": len(yr_sub),
            "High_Priority_Count": len(yr_hp),
            "Qualified_Count": len(yr_q),
            "HP_Win_Rate_20D (%)": round((r20_hp > 0).mean() * 100, 1) if not r20_hp.empty else 0.0,
            "HP_Mean_Return_20D (%)": round(r20_hp.mean(), 2) if not r20_hp.empty else 0.0,
            "HP_Median_Return_20D (%)": round(r20_hp.median(), 2) if not r20_hp.empty else 0.0,
            "HP_Win_Rate_60D (%)": round((r60_hp > 0).mean() * 100, 1) if not r60_hp.empty else 0.0,
            "HP_Mean_Return_60D (%)": round(r60_hp.mean(), 2) if not r60_hp.empty else 0.0,
            "Universe_Mean_20D (%)": round(r20_all.mean(), 2) if not r20_all.empty else 0.0,
            "HP_Alpha_20D (%)": round(r20_hp.mean() - r20_all.mean(), 2) if not r20_hp.empty and not r20_all.empty else 0.0,
        })
    df_year_analysis = pd.DataFrame(year_rows)

    # 8. Tab: MARKET_REGIME_ANALYSIS
    if "dma_50" in signals_returns_df.columns and "dma_100" in signals_returns_df.columns:
        bull_cnt = len(signals_returns_df[signals_returns_df["dma_50"] > signals_returns_df["dma_100"]])
        corr_cnt = len(signals_returns_df[signals_returns_df["dma_50"] <= signals_returns_df["dma_100"]])
    else:
        bull_cnt = len(signals_returns_df)
        corr_cnt = 0
    regime_data = [
        {"Market_Regime": "Bull Trend (50 DMA > 100 DMA)", "Description": "Favorable structural trend environment", "Sample_Size": bull_cnt, "Status": "Evaluated Point-in-Time"},
        {"Market_Regime": "Correction / Pullback (50 DMA <= 100 DMA)", "Description": "Consolidating or counter-trend environment", "Sample_Size": corr_cnt, "Status": "Evaluated Point-in-Time"},
    ]
    df_regime = pd.DataFrame(regime_data)


    # 9. Tab 8: PORTFOLIO Simulations
    port_rows = []
    for port_name, filter_mask in [
        ("Portfolio A (High Priority Only)", signals_returns_df["candidate_category"] == "HIGH_PRIORITY_CANDIDATE"),
        ("Portfolio B (Qualified Candidates)", signals_returns_df["candidate_category"] == "QUALIFIED_CANDIDATE"),
        ("Portfolio C (All Qualified & HP)", signals_returns_df["candidate_category"].isin(["HIGH_PRIORITY_CANDIDATE", "QUALIFIED_CANDIDATE"])),
    ]:
        p_sub = signals_returns_df[filter_mask]
        if not p_sub.empty:
            rets = p_sub["fwd_net_ret_20d"].dropna()
            wins = rets[rets > 0]
            losses = rets[rets < 0]
            win_rate = (len(wins) / len(rets)) * 100.0 if len(rets) > 0 else 0.0
            avg_win = wins.mean() if not wins.empty else 0.0
            avg_loss = abs(losses.mean()) if not losses.empty else 1.0
            profit_factor = (wins.sum() / abs(losses.sum())) if not losses.empty and losses.sum() != 0 else 0.0

            port_rows.append({
                "Simulation_Portfolio": port_name,
                "Total_Trades": len(p_sub),
                "Win_Rate_20D (%)": round(win_rate, 1),
                "Average_Trade_Net_20D (%)": round(rets.mean(), 2) if not rets.empty else 0.0,
                "Median_Trade_Net_20D (%)": round(rets.median(), 2) if not rets.empty else 0.0,
                "Average_Win (%)": round(avg_win, 2),
                "Average_Loss (%)": round(avg_loss, 2),
                "Profit_Factor": round(profit_factor, 2),
                "Mean_MFE (%)": round(p_sub["mfe_pct"].dropna().mean(), 2) if not p_sub["mfe_pct"].dropna().empty else 0.0,
                "Mean_MAE (%)": round(p_sub["mae_pct"].dropna().mean(), 2) if not p_sub["mae_pct"].dropna().empty else 0.0,
                "Max_Drawdown (%)": round(p_sub["max_drawdown_pct"].dropna().min(), 2) if not p_sub["max_drawdown_pct"].dropna().empty else 0.0,
            })
    df_portfolio = pd.DataFrame(port_rows)

    # Create dedicated SIGNALS table
    df_signals_view = pd.DataFrame()
    df_signals_view["checkpoint_date"] = signals_returns_df["signal_date"]
    df_signals_view["symbol"] = signals_returns_df["symbol"]
    df_signals_view["company_name"] = signals_returns_df["company_name"] if "company_name" in signals_returns_df.columns else signals_returns_df["symbol"]
    df_signals_view["close_price_at_signal"] = signals_returns_df["close"] if "close" in signals_returns_df.columns else signals_returns_df.get("latest_close", pd.Series([0.0]*len(signals_returns_df)))
    df_signals_view["score"] = signals_returns_df["composite_score"]
    df_signals_view["qualification_status"] = signals_returns_df["candidate_category"]
    df_signals_view["wyckoff_event"] = signals_returns_df["most_recent_event_type"]
    df_signals_view["signal_type"] = signals_returns_df["most_recent_event_type"]
    df_signals_view["entry_price"] = signals_returns_df["entry_price"]
    
    # Calculate Stop, Target, Risk
    entry_p = signals_returns_df["entry_price"].fillna(0.0)
    pf_tgt = signals_returns_df["pf_price_objective"] if "pf_price_objective" in signals_returns_df.columns else pd.Series([None]*len(signals_returns_df))
    stop_p = entry_p * 0.95
    target_p = [float(tgt) if pd.notna(tgt) and float(tgt) > ep else ep * 1.15 for tgt, ep in zip(pf_tgt, entry_p)]
    risk_share = entry_p - stop_p
    risk_pct = [(rs / ep * 100.0) if ep > 0 else 5.0 for rs, ep in zip(risk_share, entry_p)]
    
    df_signals_view["stop_price"] = [round(x, 2) for x in stop_p]
    df_signals_view["target_price"] = [round(x, 2) for x in target_p]
    df_signals_view["risk_per_share"] = [round(x, 2) for x in risk_share]
    df_signals_view["initial_risk_percent"] = [round(x, 2) for x in risk_pct]
    df_signals_view["signal_strength"] = signals_returns_df["composite_score"]
    df_signals_view["broad_filter_status"] = signals_returns_df["is_mechanically_qualified"] if "is_mechanically_qualified" in signals_returns_df.columns else False
    df_signals_view["mechanical_qualification"] = df_signals_view["broad_filter_status"]
    df_signals_view["explanation"] = signals_returns_df["numeric_evidence"] if "numeric_evidence" in signals_returns_df.columns else ""
    df_signals_view["data_as_of_date"] = signals_returns_df["actual_signal_date"] if "actual_signal_date" in signals_returns_df.columns else signals_returns_df["signal_date"]


    # Create dedicated TRADES table
    df_trades_view = pd.DataFrame()
    df_trades_view["signal_id"] = signals_returns_df["symbol"] + "_" + signals_returns_df["signal_date"].astype(str)
    df_trades_view["symbol"] = signals_returns_df["symbol"]
    df_trades_view["signal_date"] = signals_returns_df["signal_date"]
    df_trades_view["entry_price"] = signals_returns_df["entry_price"]
    df_trades_view["stop_price"] = df_signals_view["stop_price"]
    df_trades_view["target_price"] = df_signals_view["target_price"]
    df_trades_view["exit_date"] = signals_returns_df.get("exit_date_20d", signals_returns_df["signal_date"])
    df_trades_view["exit_price"] = signals_returns_df.get("exit_price_20d", signals_returns_df["entry_price"])
    df_trades_view["exit_reason"] = "TIME_HORIZON_20D"
    df_trades_view["holding_days"] = 20
    df_trades_view["return_percent"] = signals_returns_df["fwd_net_ret_20d"]
    
    # R Multiple: (exit_price - entry_price) / risk_per_share
    r_mult = []
    for ep, xp, rs in zip(df_trades_view["entry_price"], df_trades_view["exit_price"], df_signals_view["risk_per_share"]):
        if pd.notna(ep) and pd.notna(xp) and pd.notna(rs) and rs > 0:
            r_mult.append(round((xp - ep) / rs, 2))
        else:
            r_mult.append(0.0)
    df_trades_view["R_multiple"] = r_mult
    df_trades_view["max_favorable_excursion"] = signals_returns_df["mfe_pct"]
    df_trades_view["max_adverse_excursion"] = signals_returns_df["mae_pct"]
    df_trades_view["win_loss"] = ["WIN" if r > 0 else "LOSS" for r in df_trades_view["return_percent"].fillna(0.0)]

    # MONTHLY_SUMMARY tab
    monthly_rows = []
    for sig_dt in sorted(signals_returns_df["signal_date"].unique()):
        m_sub = signals_returns_df[signals_returns_df["signal_date"] == sig_dt]
        m_hp = m_sub[m_sub["candidate_category"] == "HIGH_PRIORITY_CANDIDATE"]
        m_q = m_sub[m_sub["candidate_category"] == "QUALIFIED_CANDIDATE"]
        m_disq = m_sub[m_sub["candidate_category"] == "DISQUALIFIED"]
        
        r20_all = m_sub["fwd_ret_20d"].dropna()
        r20_hp = m_hp["fwd_net_ret_20d"].dropna()
        
        monthly_rows.append({
            "Month_Date": sig_dt,
            "Total_Signals": len(m_sub),
            "High_Priority_Count": len(m_hp),
            "Qualified_Count": len(m_q),
            "Disqualified_Count": len(m_disq),
            "HP_Win_Rate_20D (%)": round((r20_hp > 0).mean() * 100, 1) if not r20_hp.empty else 0.0,
            "HP_Mean_Net_20D (%)": round(r20_hp.mean(), 2) if not r20_hp.empty else 0.0,
            "Universe_Mean_Gross_20D (%)": round(r20_all.mean(), 2) if not r20_all.empty else 0.0,
            "HP_Alpha_20D (%)": round(r20_hp.mean() - r20_all.mean(), 2) if not r20_hp.empty and not r20_all.empty else 0.0,
        })
    df_monthly_summary = pd.DataFrame(monthly_rows)

    # EQUITY_CURVE Tab
    eq_rows = []
    cum_ret = 100.0
    peak = 100.0
    for idx, row in df_monthly_summary.iterrows():
        m_ret = row.get("HP_Mean_Net_20D (%)", 0.0)
        if pd.notna(m_ret) and row.get("High_Priority_Count", 0) > 0:
            cum_ret = cum_ret * (1.0 + (m_ret / 100.0))
        peak = max(peak, cum_ret)
        dd = (cum_ret - peak) / peak * 100.0
        eq_rows.append({
            "Month_Date": row["Month_Date"],
            "Monthly_Return (%)": m_ret,
            "Cumulative_Index": round(cum_ret, 2),
            "High_Water_Mark": round(peak, 2),
            "Drawdown (%)": round(dd, 2),
        })
    df_equity_curve = pd.DataFrame(eq_rows)

    # DRAWDOWN Tab
    dd_rows = []
    for cat in ["HIGH_PRIORITY_CANDIDATE", "QUALIFIED_CANDIDATE", "WATCHLIST", "DISQUALIFIED"]:
        cat_sub = signals_returns_df[signals_returns_df["candidate_category"] == cat]
        if not cat_sub.empty:
            dd_series = cat_sub["max_drawdown_pct"].dropna()
            mae_series = cat_sub["mae_pct"].dropna()
            dd_rows.append({
                "Category": cat,
                "Count": len(cat_sub),
                "Mean_MAE (%)": round(mae_series.mean(), 2) if not mae_series.empty else 0.0,
                "Median_MAE (%)": round(mae_series.median(), 2) if not mae_series.empty else 0.0,
                "Worst_MAE (%)": round(mae_series.min(), 2) if not mae_series.empty else 0.0,
                "Mean_Max_Drawdown (%)": round(dd_series.mean(), 2) if not dd_series.empty else 0.0,
                "Worst_Max_Drawdown (%)": round(dd_series.min(), 2) if not dd_series.empty else 0.0,
            })
    df_drawdown = pd.DataFrame(dd_rows)

    # DATA_DICTIONARY Tab
    dict_rows = [
        {"Field": "checkpoint_date", "Type": "Date", "Description": "Historical point-in-time date on which screener was evaluated"},
        {"Field": "symbol", "Type": "String", "Description": "NSE ticker symbol"},
        {"Field": "company_name", "Type": "String", "Description": "Issuer legal company name"},
        {"Field": "close_price_at_signal", "Type": "Float", "Description": "Closing price on signal checkpoint date"},
        {"Field": "score", "Type": "Float", "Description": "0-100 composite Wyckoff score"},
        {"Field": "qualification_status", "Type": "String", "Description": "HIGH_PRIORITY_CANDIDATE, QUALIFIED_CANDIDATE, WATCHLIST, DISQUALIFIED"},
        {"Field": "wyckoff_event", "Type": "String", "Description": "Most recent detected Wyckoff schematic event"},
        {"Field": "entry_price", "Type": "Float", "Description": "Opening price on next trading day (T+1 Open)"},
        {"Field": "stop_price", "Type": "Float", "Description": "Support level / 5% default risk threshold"},
        {"Field": "target_price", "Type": "Float", "Description": "Fraser Point & Figure horizontal objective or +15% default target"},
        {"Field": "fwd_net_ret_20d", "Type": "Float", "Description": "Realized net return after 20 bars deducting 0.40% friction"},
        {"Field": "R_multiple", "Type": "Float", "Description": "Realized return expressed in units of initial risk"},
        {"Field": "mfe_pct", "Type": "Float", "Description": "Maximum Favorable Excursion (% peak upside from entry)"},
        {"Field": "mae_pct", "Type": "Float", "Description": "Maximum Adverse Excursion (% trough downside from entry)"},
    ]
    df_dict = pd.DataFrame(dict_rows)

    p17_xlsx_path = out_dir / "phase17_google_sheets_backtest.xlsx"


    for path in [xlsx_path, p17_xlsx_path]:
        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            df_readme.to_excel(writer, sheet_name="README", index=False)
            df_signals_view.to_excel(writer, sheet_name="SIGNALS", index=False)
            df_trades_view.to_excel(writer, sheet_name="TRADES", index=False)
            df_monthly_summary.to_excel(writer, sheet_name="MONTHLY_SUMMARY", index=False)
            df_score_analysis.to_excel(writer, sheet_name="SCORE_ANALYSIS", index=False)
            df_signal_type.to_excel(writer, sheet_name="WYCKOFF_ANALYSIS", index=False)
            df_equity_curve.to_excel(writer, sheet_name="EQUITY_CURVE", index=False)
            df_readme.to_excel(writer, sheet_name="PARAMETERS", index=False)
            df_summary.to_excel(writer, sheet_name="SUMMARY", index=False)
            df_year_analysis.to_excel(writer, sheet_name="YEAR_ANALYSIS", index=False)
            df_regime.to_excel(writer, sheet_name="MARKET_REGIME_ANALYSIS", index=False)
            df_benchmark.to_excel(writer, sheet_name="BENCHMARK", index=False)
            df_portfolio.to_excel(writer, sheet_name="PORTFOLIO", index=False)
            df_drawdown.to_excel(writer, sheet_name="DRAWDOWN", index=False)
            df_dict.to_excel(writer, sheet_name="DATA_DICTIONARY", index=False)

    return p17_xlsx_path


