"""Forward return analysis and performance comparison for Wyckoff setup backtests."""

from typing import Any, Sequence
import numpy as np
import pandas as pd


def compute_forward_returns(
    rolling_scores_df: pd.DataFrame,
    price_df: pd.DataFrame,
    horizons: Sequence[int] = (10, 20, 60),
    close_col: str = "Close",
    date_col: str = "Date",
) -> pd.DataFrame:
    """Compute forward percentage returns for each scored checkpoint.

    Args:
        rolling_scores_df: DataFrame generated by run_rolling_score().
        price_df: Full historical price DataFrame.
        horizons: Forward lookahead periods in bars (e.g. 10, 20, 60 daily bars).
        close_col: Price column name in price_df.
        date_col: Date column name in price_df.

    Returns:
        pd.DataFrame: rolling_scores_df augmented with fwd_return_{h}d columns.
    """
    if rolling_scores_df.empty:
        return rolling_scores_df.copy()

    df_out = rolling_scores_df.copy()
    pdf = price_df.copy()

    if date_col in pdf.columns:
        pdf[date_col] = pd.to_datetime(pdf[date_col])
        pdf = pdf.sort_values(by=date_col).reset_index(drop=True)

    prices = pdf[close_col].to_numpy()
    total_bars = len(prices)

    for h in horizons:
        fwd_returns: list[float | None] = []
        for _, row in df_out.iterrows():
            bar_idx = int(row["bar_index"])
            target_idx = bar_idx + h
            if target_idx < total_bars:
                base_price = prices[bar_idx]
                future_price = prices[target_idx]
                ret_pct = ((future_price - base_price) / base_price) * 100.0
                fwd_returns.append(round(ret_pct, 2))
            else:
                # Horizon extends beyond available historical dataset
                fwd_returns.append(np.nan)

        df_out[f"fwd_return_{h}d"] = fwd_returns

    return df_out


def summarize_forward_returns(
    df_with_returns: pd.DataFrame,
    horizons: Sequence[int] = (10, 20, 60),
    score_high_thresh: float = 60.0,
    score_low_thresh: float = 40.0,
) -> dict[str, Any]:
    """Calculate summary statistics comparing forward performance across qualification and score tiers.

    Args:
        df_with_returns: DataFrame with forward return columns.
        horizons: List of horizons to evaluate.
        score_high_thresh: Minimum score for high-score cohort (default 60.0).
        score_low_thresh: Maximum score threshold for low-score cohort (default 40.0).

    Returns:
        dict[str, Any]: Detailed metrics dictionary.
    """
    if df_with_returns.empty:
        return {"total_checkpoints": 0}

    total_checkpoints = len(df_with_returns)
    qualified_mask = df_with_returns["is_disqualified"] == False
    disqualified_mask = df_with_returns["is_disqualified"] == True
    high_score_mask = df_with_returns["composite_score"] >= score_high_thresh
    low_score_mask = df_with_returns["composite_score"] < score_low_thresh

    results: dict[str, Any] = {
        "total_checkpoints": total_checkpoints,
        "qualified_count": int(qualified_mask.sum()),
        "disqualified_count": int(disqualified_mask.sum()),
        "high_score_count": int(high_score_mask.sum()),
        "low_score_count": int(low_score_mask.sum()),
        "horizons": {},
    }

    for h in horizons:
        col = f"fwd_return_{h}d"
        if col not in df_with_returns.columns:
            continue

        q_rets = df_with_returns.loc[qualified_mask, col].dropna()
        dq_rets = df_with_returns.loc[disqualified_mask, col].dropna()
        high_rets = df_with_returns.loc[high_score_mask, col].dropna()
        low_rets = df_with_returns.loc[low_score_mask, col].dropna()

        def _stats(series: pd.Series) -> dict[str, Any]:
            if series.empty:
                return {"count": 0, "mean_return_pct": 0.0, "win_rate_pct": 0.0, "median_return_pct": 0.0}
            return {
                "count": len(series),
                "mean_return_pct": round(float(series.mean()), 2),
                "median_return_pct": round(float(series.median()), 2),
                "win_rate_pct": round(float((series > 0).mean() * 100.0), 1),
            }

        results["horizons"][f"{h}d"] = {
            "qualified": _stats(q_rets),
            "disqualified": _stats(dq_rets),
            "high_score": _stats(high_rets),
            "low_score": _stats(low_rets),
        }

    return results
